### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by xhe123** [RHQE/pylarion-cmd#1]
- [x]   Line 6: getopt

If not using command line module, should use argparse instead.

https://docs.python.org/2/library/getopt.html
According to docs:
"...Users who are unfamiliar with the C getopt() function or who would like to write less code and get better help and error messages should consider using the argparse module instead."
- [x]  Line 14: usage

Why not use a cmd line module such as click (http://click.pocoo.org/5/) that will do all this work for you?

It makes it much easier for long term maintenance.
- [x]   Line 54: ConfigParser
  use SafeConfigParser instead.
  https://docs.python.org/2/library/configparser.html
  "... New applications should prefer this version if they don’t need to be compatible with older versions of Python."

Look at the latest version of base_pylarion.py and try to keep it similar.
- [x]   Line 58: fdict["space"] = cfile.get('cmd', 'space')
  Why is the user defining a space in the config file? Is your expectation that every uyser only uses one space? Is this true in all projects that will use this cli?
- [x]  Line 59: fdict["project"] = cfile.get('webservice', 'default_project')
  default_project is a class attribute of every pylarion class, so you udon't need to get it here. You can just use it like Document.default_project
- [x]  Line 61: fdict["user"] = cfile.get('webservice', 'user')
  logged_in_user_id is a class attribute of every pylarion class, so you udon't need to get it here. You can just use it like Document.logged_in_user_id
- [x]  Line 62: try
  use defaults instead of try/except.
- [x]  Line 58:         fdict["space"] = cfile.get('cmd', 'space')
     :         fdict["project"] = cfile.get('webservice', 'default_project')
     :         fdict["output"] = cfile.get('cmd', 'output')
     :         fdict["user"] = cfile.get('webservice', 'user')
     :         try:
     :             fdict["plan_id"] = cfile.get('cmd', 'plan_id')
     :             fdict["assignee"] = cfile.get('cmd', 'assignee')
  allow environment variables:
  example:
  fdict["space"] = os.environ.get("POLARION_CMD_SPACE") or cfile.get('cmd', 'space')
- [x]  Line 67: ConfigParser
  Shouldn't this be a fatal error?
  I suggest letting the exception happen and be raised up to the user. The error message is also incorrect because the config file is not always in ~/.pylarion.
  Also the file might be there. The error you are handling is that the section is not there.
- [x]  Line 87:         elif o in ["--document", "-d"]:
     :             config["document"] = a
     :         elif o in ["--workitem_type", "-t"]:
     :             config["workitem_type"] = a
     :         elif o in ["--caseid", "-i"]:
     :             config["caseid"] = a
     :         elif o in ["--requirement", "-q"]:
     :             config["requirement"] = a
     :         elif o in ["--steps", "-s"]:
     :             config["steps"] = a
     :         elif o in ["--status", "-u"]:
     :             config["status"] = a
     :         elif o in ["--links", "-l"]:
     :             config["links"] = a
     :         elif o in ["--run", "-r"]:
     :             config["run"] = a
     :         elif o in ["--template", "-m"]:
     :             config["template"] = a
     :         elif o in ["--result", "-o"]:
     :             config["result"] = a
     :         elif o in ["--query", "-e"]:
     :             config["query"] = a
     :         elif o in ["--comment", "-c"]:
     :             config["comment"] = a
     :         elif o in ["--plan_id", "-p"]:
     :             config["plan_id"] = a
     :         elif o in ["--planned_in", "-n"]:
     :             config["plannedin"] = a
     :         elif o in ["--assignee", "-a"]:
     :             config["assignee"] = a
  All of this code could be done with a dictionary and without all if..else structure.
  dictionary to map -d to --dictionary, for loop similar to:

config[o[2:]] = a
- [x]  Line 125:     try:
      :         if fdict[param1]:
      :             return True
      :         else:
      :             return False
      :     except:
      :         pass
  use fdict.get no need for exception
- [x]   Line 137:     if who == "root":
      :         config_file = "/root/.pylarion"
      :     else:
      :         config_file = "/home/%s/.pylarion" % who
  Please see most recent version of base_polarion.py for location of config file.
- [x]  Line 148:     except:
  use except Exception so that it doesn't catch SystemExit and KeyboardInterrupt type errors.

Line 149: print "Failed to get information from pylarion.cfg file
There might be a lot of other reasons why the above has failed. For example, Polarion might be down or there might be a network problem, or the user's password might be wrong.

I suggest either not using an exception and letting the error raise by itself, or passing in the error msg so the user can see what the actual problem is.
- [x]  Line 201:        elif "run" in con_dict or ("query" or "template") in con_dict:
  can you write a comment with the logic here?

https://code.engineering.redhat.com/gerrit/#/c/80881/1/src/pylarion/cli/CliDoc.py
File src/pylarion/cli/CliDoc.py:
- [x]  Line 33:         self.project_id = default_project
  No need to pass in parm. an access it as Document.default_project
- [x]  Line 36: document_list
  Shouldn't this be = [] as workitem_list?
- [x]  Line 40: in
  from
- [x]  Line 59: required if project_id is given
  no project_id argument
- [x]  Line 60: item_type: the item type are one of these items:
     :                        testcase
     :                        requirement
  no item_type argument
- [x]  Line 73: def _columnar_display(self, list, pagewidth=170):
  This function is not use by anything else. Does it have a purpose.
- [x]  Line 73: list
  list is a python internal object. It should not be the name of a variable/parameter.
- [x]  Line 81:         maxlen = 0
     :         for item in list:
     :             lt = len(str(item))
     :             if lt > maxlen:
     :                 maxlen = lt
     :         maxlen += 2  # space it out a little more
  ma[len(item) for item in list]) + 2
- [x]  Line 87: int
  int / int is an integer divide.
  No need to call int function.
- [x]  Line 106: lst_doc = self.document_list
  why not just use self.document_list?
- [x]  Line 109: print "Totally Document: %d|loanding ...\n" % num_doc
  what does this mean?
  Maybe:
  Total Documents: %s "

Also, because this isn't asynchronous, the print doesn't happen until after the docs are already gotten from the server. So Loading message will always come at almost the exact same time as the list itself.
- [x]  Line 114:         for i in range(0, len(lst_doc)):
      :             print "%d: %s" % (i, lst_doc[i].document_name)
  maybe
  for i, doc in enumerate(lst_doc):
  print "%d: %s" % (i, doc.document_name)
- [x]  Line 144:             self._list_docs()
  after listing all the docs, why would someone want to search to see if the one he already sees is there?
- [x]  Line 151:         lst_doc = Document.get_documents(self.project_id, self.space, field)
      :
      :         for i in range(0, len(lst_doc)):
      :             c_doc = lst_doc[i].document_name
      :             print c_doc
      :             if document_name in c_doc or c_doc in document_name:
      :                 if is_exists is True:
      :                     print "\nIt's successfully to search the document!\n"
      :                     return 0
  Why not do a document query instead of getting all documents and parsing through them?
  Why print all the document names until the one you are looking for?
- [x]  Line 181:         for i in range(0, len(self.workitem_list)):
      :             if self.workitem_list[i].type == workitem_type:
      :                 print "%s   %s" % (self.workitem_list[i].work_item_id,
      :                                    self.workitem_list[i].title)
  use enumerate -- see comment above
- [x]  Line 186: def get_docs(self, dpath):
  This file written here isn't used by any opther functions. What is its purpose?
- [x]  Line 186: get_docs
  change name to cache_docs or something similar. The other get_\* functions don't write to a file so this is confusing

**Comment by lulinqing** [comment]
seems all fixed in #4
